name: Build and Deploy WebGL

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   # Pass your license file here

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: "2022.3.17f1"  # match your Editor version

      - name: Build WebGL
        run: |
          Unity -batchmode -nographics -quit \
            -projectPath . \
            -buildTarget WebGL \
            -executeMethod BuildScript.PerformBuild

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Build/WebGL
